// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQHemYE4X682SBGBwSibzIQlKJRgyYQYc',
    appId: '1:511369017673:web:c59b8d394c5cead5254298',
    messagingSenderId: '511369017673',
    projectId: 'agendamento-clube-31ec1',
    authDomain: 'agendamento-clube-31ec1.firebaseapp.com',
    databaseURL: 'https://agendamento-clube-31ec1-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-clube-31ec1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL8CLkJzZfHXDr5PZwVSzI_Xv64cMsKeU',
    appId: '1:511369017673:android:d2f76d4c177c2742254298',
    messagingSenderId: '511369017673',
    projectId: 'agendamento-clube-31ec1',
    databaseURL: 'https://agendamento-clube-31ec1-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-clube-31ec1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4TqlFbbCWVJrED0oOCa2-_tdRoj7Xjx8',
    appId: '1:511369017673:ios:4aea35735a4a1a1a254298',
    messagingSenderId: '511369017673',
    projectId: 'agendamento-clube-31ec1',
    databaseURL: 'https://agendamento-clube-31ec1-default-rtdb.firebaseio.com',
    storageBucket: 'agendamento-clube-31ec1.appspot.com',
    iosBundleId: 'com.example.agendamentoClube',
  );
}
